language: node_js
node_js: 
- "8.11.3"
before_install:
- npm install -g mocha
- npm install 
script: 
- npm test
after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
after_test:
- npm install -g coveralls 
- npm run coveralls